import type { Metadata } from "next";
import {Inter_Tight } from "next/font/google";
import "./globals.css";
import { RightBar } from "@/components/right-bar";
import { LeftBar } from "@/components/left-bar";

const Inter = Inter_Tight({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.className} antialiased`}
      >
         {children}
      </body>
    </html>
  );
}
